#!/bin/sh

java -cp ./target/classes:$HOME/.m2/repository/net/sf/squirrel-sql/thirdparty-non-maven/java-cup/0.11a/java-cup-0.11a.jar:$HOME/.m2/repository/com/beust/jcommander/1.30/jcommander-1.30.jar -ea net.alexweinert.coolc.Main "$@"
